INSERT INTO [dbo].[users] (userid_domain, userid_email, username, role, avatar) VALUES ('2022a.shiran.bibi', 'a@b.com', 'admin user', 'MANAGER', 'jj');
INSERT INTO [dbo].[users] (userid_domain, userid_email, username, role, avatar) VALUES ('2022a.shiran.bibi', 'ab@b.com', 'John Doe', 'PLAYER', 'jj');
INSERT INTO [dbo].[users] (userid_domain, userid_email, username, role, avatar) VALUES ('2022a.shiran.bibi', 'abc@b.com', 'Jane Doe', 'PLAYER', 'jj');
INSERT INTO [dbo].[users] (userid_domain, userid_email, username, role, avatar) VALUES ('2022a.shiran.bibi', 'abcd@b.com', 'admin user 2', 'MANAGER', 'jj');
INSERT INTO [dbo].[users] (userid_domain, userid_email, username, role, avatar) VALUES ('2022a.shiran.bibi', 'fedcba@b.com', 'admin user 3', 'MANAGER', 'jj');
INSERT INTO [dbo].[users] (userid_domain, userid_email, username, role, avatar) VALUES ('2022a.shiran.bibi', 'p@p.com', 'player user', 'PLAYER', 'jj');
INSERT INTO [dbo].[users] (userid_domain, userid_email, username, role, avatar) VALUES ('2022a.shiran.bibi', 'm@m.com', 'manager user', 'MANAGER', 'jj');

INSERT INTO [dbo].[instances] ( instanceid_domain, instanceid_id, active, created_by ,created_time_stamp ,instance_attributes ,location,name ,type ,parent_instanceid_domain ,parent_instanceid_id) values ('2022a.shiran.bibi','1',1,'{"userId":{"domain":"2022a.shiran.bibi","email":"m@m.com"}}',GETDATE(),'{"key1":"can be set to any value you wish","key2":"you can also name the attributes any name you like","key3":6.2,"key4":false}','{"lat":32.115139,"lng":34.817804}','demo instance','dummyInstanceType',null,null);
INSERT INTO [dbo].[instances] ( instanceid_domain, instanceid_id, active, created_by ,created_time_stamp ,instance_attributes ,location,name ,type ,parent_instanceid_domain ,parent_instanceid_id) values ('2022a.shiran.bibi','2',1,'{"userId":{"domain":"2022a.shiran.bibi","email":"m@m.com"}}',GETDATE(),'{"key1":"can be set to any value you wish","key2":"you can also name the attributes any name you like","key3":6.2,"key4":false}','{"lat":32.115139,"lng":34.817804}','demo instance','dummyInstanceType',null,null);
INSERT INTO [dbo].[instances] ( instanceid_domain, instanceid_id, active, created_by ,created_time_stamp ,instance_attributes ,location,name ,type ,parent_instanceid_domain ,parent_instanceid_id) values ('2022a.shiran.bibi','3',0,'{"userId":{"domain":"2022a.shiran.bibi","email":"m@m.com"}}',GETDATE(),'{"key1":"can be set to any value you wish","key2":"you can also name the attributes any name you like","key3":6.2,"key4":false}','{"lat":32.115139,"lng":34.817804}','demo instance','dummyInstanceType',null,null);

INSERT INTO [dbo].[activities] (activityid_domain, activityid_id ,activity_attributes ,created_time_stamp ,instanceid_domain ,instanceid_id, invoked_by, type) values ('2022a.shiran.bibi','1','{"item1":{"number":"123","desc":"Blue jeans"},"item2":{"number":"222","desc":"Winter coat against a storm that does not exist"}}', GETDATE(), '2022a.shiran.bibi', '2', null,'PurchaseItem');